--Creacion de tablas--

--TABLA FUNCIONARIO--
CREATE TABLE FUNCIONARIOS(
	ID_FUNCIONARIO int identity CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO1 VARCHAR(20) NOT NULL,
	APELLIDO2 VARCHAR(20) NOT NULL,
	CEDULA VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	PUESTO_TRABAJO VARCHAR (30) NOT NULL,
	BORRADO_FUNCIONARIO bit 
);
--TABLA HORARIOS--
CREATE TABLE HORARIOS(
	ID_HORARIO int identity CONSTRAINT PK_HORARIOS PRIMARY KEY NOT NULL,
	ID_FUNCIONARIO int CONSTRAINT FK_HORARIOS FOREIGN KEY REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)NOT NULL,
	DIA_INICIO varchar(20) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	BORRADO_HORARIO bit 
);
--TABLA ESPECIALIDADES--
CREATE TABLE ESPECIALIDADES(
	ID,
	ID_FUNCIONARIO int CONSTRAINT FK_ESPECIALIDADES FOREIGN KEY REFERENCES FUNCIONARIOS(ID_FUNCIONARIO) NOT NULL,
	NOMBRE varchar(30) NOT NULL,
	DESCRIPCION varchar(200) NOT NULL,
	BORRADO_ESPECIALIDAD bit 
);

--TABLA PACIENTES--
CREATE TABLE PACIENTES(
	ID_PACIENTE int identity CONSTRAINT PK_PACIENTE PRIMARY KEY NOT NULL,
	NOMBRE_P varchar(20) NOT NULL,
	APELLIDO1_P varchar(20) NOT NULL,
	APELLIDO2_P varchar(20) NOT NULL,
	CEDULA varchar(20) NOT NULL,
	NACIONALEXTRANJERO varchar(10) CONSTRAINT CK_ESTADO CHECK(NACIONALEXTRANJERO IN('NACIONAL', 'EXTRANJERO',upper(NACIONALEXTRANJERO))) DEFAULT 'NACIONAL' NOT NULL,
	FECHANACIMIENTO date NOT NULL,
	TELEFONO varchar(11) NOT NULL,
	BORRADO_PACIENTE bit 
);

--TABLA USUARIOS--
CREATE TABLE USUSARIOS(
	ID_USUSARIO int identity CONSTRAINT PK_USUSARIOS PRIMARY KEY NOT NULL,
	ID_PACIENTE int CONSTRAINT FK_PACIENTES FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE) NOT NULL,
	ID_FUNCIONARIO int CONSTRAINT FK_FUNCION FOREIGN KEY REFERENCES FUNCIONARIOS(ID_FUNCIONARIO) NOT NULL,
	CONTRASEÑA varchar(25) NOT NULL,
	ROLES varchar(50) NOT NULL,
	BORRADO_USUSARIO bit 
);

--TABLA BITACORAUSUARIOS--
CREATE TABLE BITACORA_USUARIOS(
	ID_REGISTRO_USUSARIO int identity CONSTRAINT PK_BITACORA_USU PRIMARY KEY NOT NULL,
	ID_USUSARIO int CONSTRAINT FK_USUARIOS FOREIGN KEY REFERENCES USUSARIOS(ID_USUSARIO) NOT NULL,
	FECHA_HORA date NOT NULL,
	ACCION varchar(200) NOT NULL,
	BORRADO_BITACORA bit 
);

--TABLA CITAS--
CREATE TABLE CITAS(
	ID_CITA int identity CONSTRAINT PK_CITAS PRIMARY KEY NOT NULL,
	ID_PACIENTE int CONSTRAINT FK_CITAS_PACIENTES FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE) NOT NULL,
	ID_FUNCIONARIO int CONSTRAINT FK_CITAS_FUNCIONARIOS FOREIGN KEY REFERENCES FUNCIONARIOS(ID_FUNCIONARIO) NOT NULL,
	FECHA date NOT  NULL,
	HORA_CITA TIME NOT NULL,
	BORRADO_CITAS bit 
);
--TABLA PAGOS--
CREATE TABLE PAGOS(
	ID_PAGO int identity CONSTRAINT PK_PAGOS PRIMARY KEY NOT NULL,
	ID_CITA int CONSTRAINT FK_PAGOS_CITAS FOREIGN KEY REFERENCES CITAS(ID_CITA) NOT NULL,
	MONTO decimal NOT NULL,
	METODO_PAGO varchar(20) NOT NULL,
	BORRADO_PAGO bit
);

--TABLA REGISTROPAGOS--
CREATE TABLE REGISTRO_PAGOS(
	ID_PAGO int CONSTRAINT FK_REPAGOS FOREIGN KEY REFERENCES PAGOS(ID_PAGO) NOT NULL,
	FECHA date NOT NULL,
	MONTO decimal NOT NULL,
	METODO_PAGO varchar(20) NOT NULL,
	BORRADO_REGISTRO_PAGO bit 
);

--TABLA MEDICAMENTOS--
CREATE TABLE MEDICAMENTOS(
	ID_MEDICAMENTO int identity CONSTRAINT PK_MEDICAMENTOS PRIMARY KEY NOT NULL,
	NOMBRE_MEDICAMENTO varchar(50) NOT NULL,
	DESCRIPCION varchar(200) NULL,
	BORRADO_MEDICAMENTO bit 
);
--TABLA HISTORIAL CLINICO--
CREATE TABLE HISTORIAL_CLINICO(
	ID_HISTORIAL int identity CONSTRAINT PK_HISTORIAL PRIMARY KEY,
	ID_PACIENTE int CONSTRAINT FK_HISTORIAL_PACIENTES FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE) NOT NULL,
	ID_MEDICAMENTO int CONSTRAINT FK_HISTORIAL_MEDICAMENTOS FOREIGN KEY REFERENCES MEDICAMENTOS(ID_MEDICAMENTO) NOT NULL,
	FECHA_REGISTRO date NOT NULL,
	DIAGNOSTICO varchar(400) NOT NULL,
	BORRADO_HISTCLINICO bit 
);

CREATE TABLE MEDICAMENTOS_HISTORIAL(
	ID_MEDICAMENTO int Constraint FK_MEDICAMENTO FOREIGN KEY REFERENCES MEDICAMENTOS(ID_MEDICAMENTO) NOT NULL,
	ID_HISTORIAL int CONSTRAINT FK_HISTORIAL FOREIGN KEY REFERENCES HISTORIAL_CLINICO(ID_HISTORIAL) NOT NULL
);



